In [51]:
#NORMALIZATION PROBLEM

In [27]:
import numpy as np

In [29]:
X = np.random.random((5,5))#Random number generator + array para isang bagsakan
X

array([[0.61946141, 0.25557106, 0.08552949, 0.30431025, 0.56896247],
       [0.66752974, 0.71067315, 0.91519912, 0.71178586, 0.09291331],
       [0.40289745, 0.68607345, 0.42051277, 0.35266195, 0.20587494],
       [0.58058057, 0.89513918, 0.98031607, 0.319478  , 0.63647792],
       [0.50601845, 0.1090706 , 0.70661489, 0.89795022, 0.40142645]])

In [31]:
a = np.mean(X) #mean function para shortcut sa mean
a

0.5213211515476893

In [33]:
b = np.std(X) #standard deviation function for std ez
b

0.26074262216503874

In [35]:
normalized_X = a/b #normalize X manually
normalized_X

1.999370671426767

In [39]:
np.save('X_normalized',normalized_X) #save X to as X_normalized.npy

In [53]:
c = np.load('X_normalized.npy') #testing lng hehe
c

array(1.99937067)

In [55]:
#DIVISIBLE BY 3 PROBLEM

In [95]:
Y = np.arange(1,101,1)#put values in array from 1-100
Y

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [97]:
Y.resize(10,10)#resize array to 10x10
Y

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [99]:
Y = Y*Y #multiply array to self to get squares
Y

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [119]:
Y #finalize output ng array para d na gumulo

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [105]:
f = 0 #setup counter

In [113]:
for y in Y: #nested for loop para bilangin mga divisble by 3
    for x in y:
        if x % 3 == 0:
            f = f+1
        else:
            pass        

In [121]:
f #print resultsss

33

In [123]:
np.save('div_by_3',f) #save results as div_by_3.npy