In [7]:
#NORMALIZATION PROBLEM

In [9]:
import numpy as np

In [11]:
X = np.random.random((5,5))#Random number generator + array para isang bagsakan
X

array([[0.24634467, 0.77654219, 0.60324106, 0.65918588, 0.80705286],
       [0.74667041, 0.68991197, 0.5500619 , 0.99691078, 0.96635228],
       [0.96887749, 0.6080559 , 0.23330189, 0.69627838, 0.48775135],
       [0.98681383, 0.21178697, 0.70567144, 0.32907591, 0.17487532],
       [0.95076701, 0.42211921, 0.16326231, 0.65818858, 0.57129891]])

In [13]:
a = np.mean(X) #mean function para shortcut sa mean
a

0.6084159397095101

In [15]:
b = np.std(X) #standard deviation function for std ez
b

0.2632434361454343

In [17]:
normalized_X = (X-a)/b #normalize X 
normalized_X

array([[-1.37542372e+00,  6.38672128e-01, -1.96581469e-02,
         1.92863100e-01,  7.54575030e-01],
       [ 5.25196260e-01,  3.09584265e-01, -2.21673304e-01,
         1.47580066e+00,  1.35971609e+00],
       [ 1.36930878e+00, -1.36770795e-03, -1.42497018e+00,
         3.33768785e-01, -4.58376459e-01],
       [ 1.43744473e+00, -1.50670032e+00,  3.69450809e-01,
        -1.06114717e+00, -1.64691900e+00],
       [ 1.30051133e+00, -7.07697524e-01, -1.69103412e+00,
         1.89074560e-01, -1.40998872e-01]])

In [19]:
np.save('X_normalized',normalized_X) #save X to as X_normalized.npy

In [21]:
c = np.load('X_normalized.npy') #for double checking
c

array([[-1.37542372e+00,  6.38672128e-01, -1.96581469e-02,
         1.92863100e-01,  7.54575030e-01],
       [ 5.25196260e-01,  3.09584265e-01, -2.21673304e-01,
         1.47580066e+00,  1.35971609e+00],
       [ 1.36930878e+00, -1.36770795e-03, -1.42497018e+00,
         3.33768785e-01, -4.58376459e-01],
       [ 1.43744473e+00, -1.50670032e+00,  3.69450809e-01,
        -1.06114717e+00, -1.64691900e+00],
       [ 1.30051133e+00, -7.07697524e-01, -1.69103412e+00,
         1.89074560e-01, -1.40998872e-01]])

In [55]:
#DIVISIBLE BY 3 PROBLEM

In [23]:
Y = np.arange(1,101,1)#put values in array from 1-100
Y

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [25]:
Y.resize(10,10)#resize array to 10x10
Y

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [27]:
Y = Y*Y #multiply array to self to get squares
Y

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [29]:
Y #finalize output ng array para d na gumulo

array([[    1,     4,     9,    16,    25,    36,    49,    64,    81,
          100],
       [  121,   144,   169,   196,   225,   256,   289,   324,   361,
          400],
       [  441,   484,   529,   576,   625,   676,   729,   784,   841,
          900],
       [  961,  1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,
         1600],
       [ 1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
         2500],
       [ 2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,  3481,
         3600],
       [ 3721,  3844,  3969,  4096,  4225,  4356,  4489,  4624,  4761,
         4900],
       [ 5041,  5184,  5329,  5476,  5625,  5776,  5929,  6084,  6241,
         6400],
       [ 6561,  6724,  6889,  7056,  7225,  7396,  7569,  7744,  7921,
         8100],
       [ 8281,  8464,  8649,  8836,  9025,  9216,  9409,  9604,  9801,
        10000]])

In [31]:
f = 0 #setup counter

In [33]:
for y in Y: #nested for loop para bilangin mga divisble by 3
    for x in y:
        if x % 3 == 0:
            f = f+1
        else:
            pass        

In [35]:
f #print resultsss

33

In [37]:
np.save('div_by_3',f) #save results as div_by_3.npy

In [41]:
np.load('div_by_3.npy')

array(33)